# Generated by Django 5.1.4 on 2025-01-27 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('date', models.DateField(null=True)),
                ('image', models.ImageField(default='null.jpg', upload_to='Movie')),
            ],
        ),
    ]
