# Generated by Django 5.1.4 on 2025-01-28 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='video',
            field=models.FileField(null=True, upload_to='Movievideo'),
        ),
    ]
