# Generated by Django 5.1.4 on 2025-01-29 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='genre_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.genre'),
        ),
    ]
