# Generated by Django 5.1.4 on 2025-02-21 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_movies_genre_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
