# Generated by Django 5.1.4 on 2025-02-21 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_movies_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='likes',
        ),
    ]
