# Generated by Django 5.1.4 on 2025-02-25 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_remove_movies_likes'),
        ('User', '0025_comment_dislikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='liked_users',
            field=models.ManyToManyField(blank=True, related_name='liked_movies', to='User.user'),
        ),
        migrations.AddField(
            model_name='movies',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
