# Generated by Django 5.1.4 on 2025-02-25 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_movies_liked_users_movies_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='liked_users',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='likes',
        ),
    ]
