# Generated by Django 5.1.4 on 2025-02-26 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_remove_movies_liked_users_remove_movies_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movies',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
