# Generated by Django 5.1.4 on 2025-02-26 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0011_movies_dislikes_movies_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movies',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
