# Generated by Django 5.1.4 on 2025-01-27 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_movie_email_movie_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie',
            new_name='User',
        ),
    ]
