# Generated by Django 5.1.4 on 2025-01-27 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_rename_movie_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
