# Generated by Django 5.1.4 on 2025-01-31 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
