# Generated by Django 5.1.4 on 2025-02-04 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_user_name_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='message',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
