# Generated by Django 5.1.4 on 2025-02-04 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_complaint_remove_user_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='message',
            new_name='messages',
        ),
    ]
