# Generated by Django 5.1.4 on 2025-02-05 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_rename_message_complaint_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genreoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genname', models.CharField(max_length=25, null=True)),
                ('genimage', models.ImageField(upload_to='GenImage')),
            ],
        ),
    ]
