# Generated by Django 5.1.4 on 2025-02-05 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_genreoption'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genreoption',
        ),
    ]
