# Generated by Django 5.1.4 on 2025-02-07 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_delete_genreoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactname', models.CharField(max_length=25, null=True)),
                ('contactemail', models.EmailField(max_length=254)),
                ('contactphone', models.IntegerField(null=True)),
                ('categories', models.CharField(max_length=25, null=True)),
            ],
        ),
    ]
