# Generated by Django 5.1.4 on 2025-02-07 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_contactus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='contactemail',
            new_name='cemail',
        ),
        migrations.RenameField(
            model_name='contactus',
            old_name='contactname',
            new_name='cname',
        ),
        migrations.RenameField(
            model_name='contactus',
            old_name='contactphone',
            new_name='cphone',
        ),
    ]
