# Generated by Django 5.1.4 on 2025-02-12 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0013_rename_contactemail_contactus_cemail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Enames', models.CharField(max_length=25, null=True)),
                ('Eemails', models.EmailField(max_length=254)),
                ('Ephones', models.IntegerField(null=True)),
            ],
        ),
    ]
