# Generated by Django 5.1.4 on 2025-02-12 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0014_edits'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Edits',
        ),
    ]
