# Generated by Django 5.1.4 on 2025-02-19 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0016_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comments',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
