# Generated by Django 5.1.4 on 2025-02-19 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0017_comment_parent_comment_alter_comment_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
