# Generated by Django 5.1.4 on 2025-02-19 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0018_comment_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='cmtname',
        ),
    ]
