# Generated by Django 5.1.4 on 2025-02-19 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0019_rename_name_comment_cmtname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='cmtname',
        ),
    ]
