# Generated by Django 5.1.4 on 2025-02-20 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0020_remove_comment_cmtname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent_comment',
        ),
    ]
