# Generated by Django 5.1.4 on 2025-02-20 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_movies_genre_id'),
        ('User', '0021_remove_comment_parent_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.movies'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
