# Generated by Django 5.1.4 on 2025-02-25 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0026_remove_comment_dislikes_remove_comment_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='MovieLike',
        ),
    ]
