# Generated by Django 5.1.4 on 2025-02-26 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0028_moviereaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviereaction',
            name='reaction',
            field=models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=10, null=True),
        ),
    ]
