# Generated by Django 5.1.4 on 2025-03-11 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0030_alter_moviereaction_reaction_watchlater'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
