# Generated by Django 5.1.4 on 2025-03-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0034_subscription_remove_usersubscription_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
